# get all songs
GET http://localhost:3000/songs

### get song by id
GET http://localhost:3000/songs/1

### create song
POST http://localhost:3000/songs HTTP/1.1
content-type: application/json

{
    "title": "Testing 2",
    "author": ["The moon"],
    "releaseDate": "2021-11-29",
    "duration": "02:35"
}

### update song
PUT http://localhost:3000/songs/1

### delete song
DELETE http://localhost:3000/songs/1


